package com.bjbs.haji.business.models;
// Generated Jan 24, 2020 10:09:35 AM by Hibernate Tools 4.3.1.Final

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * MataUang generated by hbm2java
 */
@Entity
@Table(name = "mata_uang", schema = "public")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class MataUang implements java.io.Serializable {

	private static final long serialVersionUID = -7329439347718738868L;

	@Id
	@Column(name = "mata_uang_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_mata_uang_mata_uang_id_seq")
	@SequenceGenerator(name="generator_mata_uang_mata_uang_id_seq", sequenceName="mata_uang_mata_uang_id_seq", schema = "public", allocationSize = 1)
	private long mataUangId;

	@Column(name = "kode_mata_uang", nullable = false, length = 3)
	private String kodeMataUang;

	@Column(name = "mata_uang", length = 10)
	private String mataUang;

	@Column(name = "description")
	private String description;

	@Column(name = "status_active")
	private Boolean statusActive;

	public MataUang(long mataUangId) {
		this.mataUangId = mataUangId;
	}
}
