package com.bjbs.haji.business.models;
// Generated Jan 24, 2020 10:09:35 AM by Hibernate Tools 4.3.1.Final

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Pendidikan generated by hbm2java
 */
@Entity
@Table(name = "pendidikan", schema = "public")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Pendidikan implements java.io.Serializable {

	private static final long serialVersionUID = -327991680205669742L;

	@Id
	@Column(name = "pendidikan_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_pendidikan_pendidikan_id_seq")
	@SequenceGenerator(name="generator_pendidikan_pendidikan_id_seq", sequenceName="pendidikan_pendidikan_id_seq", schema = "public", allocationSize = 1)
	private long pendidikanId;

	@Column(name = "pendidikan", length = 40)
	private String pendidikan;

	@Column(name = "status_active")
	private Boolean statusActive;

	@Column(name = "kode_pendidikan")
	private String kodePendidikan;

	@Column(name = "kode_pendidikan_core")
	private String kodePendidikanCore;

	public Pendidikan(long pendidikanId) {
		this.pendidikanId = pendidikanId;
	}
}
