package com.bjbs.haji.business.models;
// Generated Jan 24, 2020 10:09:35 AM by Hibernate Tools 4.3.1.Final

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PelunasanHaji generated by hbm2java
 */
@Entity
@Table(name = "setoran_pelunasan", schema = "public")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SetoranPelunasan implements java.io.Serializable {

	private static final long serialVersionUID = -971550932491797707L;

	@Id
	@Column(name = "setoran_pelunasan_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_pelunasan_haji_pelunasan_haji_id_seq")
	@SequenceGenerator(name="generator_pelunasan_haji_pelunasan_haji_id_seq", sequenceName="pelunasan_haji_pelunasan_haji_id_seq", schema = "public", allocationSize = 1)
	private long setoranPelunasanId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "channel_id", nullable = false)
	private Channel channel;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mata_uang_id", nullable = false)
	private MataUang mataUang;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_transaksi_id")
	private StatusTransaksi statusTransaksi;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="tipe_haji_id")
	private TipeHaji tipeHaji;

	@Column(name = "branch_code")
	private String branchCode;

	@Column(name = "transaction_id")
	private String transactionId;

	@Column(name = "no_rekening")
	private String noRekening;

	@Column(name = "no_porsi")
	private String noPorsi;

	@Column(name = "nama_jemaah")
	private String namaJemaah;

	@Column(name = "embarkasi")
	private String embarkasi;

	@Column(name = "tanggal_transaksi")
	private Date tanggalTransaksi;

	@Column(name = "nilai_setoran_awal")
	private BigInteger nilaiSetoranAwal;

	@Column(name = "nominal_setoran")
	private BigInteger nominalSetoran;

	@Column(name = "biaya_bpih")
	private BigInteger biayaBpih;

	@Column(name = "kurs")
	private BigInteger kurs;

	@Column(name = "bpih_dalam_rupiah")
	private BigInteger bpihDalamRupiah;

	@Column(name = "sisa_pelunasan")
	private BigInteger sisaPelunasan;

	@Column(name = "flag_lunas_tunda")
	private short flagLunasTunda;

	@Column(name = "tahun_tunda")
	private String tahunTunda;

	@Column(name = "no_pihk")
	private String noPihk;

	@Column(name = "nama_pihk")
	private String namaPihk;

	@Column(name = "jenis_kelamin")
	private short jenisKelamin;

	@Column(name = "nama_ayah")
	private String namaAyah;

	@Column(name = "tempatLahir")
	private String tempatLahir;

	@Column(name = "tanggalLahir", columnDefinition = "DATE")
	private Date tanggalLahir;

	@Column(name = "tahun_pelunasan_hijriah")
	private String tahunPelunasanHijriah;

	@Column(name = "alamat")
	private String alamat;

	@Column(name = "kelurahan")
	private String kelurahan;

	@Column(name = "kecamatan")
	private String kecamatan;

	@Column(name = "kabupaten_kota")
	private String kabupatenKota;

	@Column(name = "provinsi")
	private String provinsi;

	@Column(name = "kode_pos")
	private String kodePos;

	@Column(name = "namaBank")
	private String namaBank;

	@Column(name = "namaCabang")
	private String namaCabang;

	@Column(name = "alamat_cabang")
	private String alamatCabang;

	@Column(name = "umur_tahun")
	private String umurTahun;

	@Column(name = "umur_bulan")
	private String umurBulan;

	@Column(name = "tahunPelunasanMasehi")
	private String tahunPelunasanMasehi;

	@Column(name = "checksum")
	private String checksum;

	@Column(name = "ret_ref_number")
	private String retRefNumber;

	@Column(name = "system_trace_number")
	private String systemTraceNumber;

	@Column(name = "terminal_id")
	private String terminalId;

	@Column(name = "nama_nasabah")
	private String namaNasabah;

	@Column(name = "created_date", columnDefinition = "DATE")
	private Date createdDate;

	@Column(name = "created_by")
	private String createdBy;

	@Column(name = "updated_date", columnDefinition = "DATE")
	private Date updatedDate;

	@Column(name = "updated_by")
	private String updatedBy;

}
