package com.bjbs.haji.business.models;
// Generated Jan 24, 2020 10:09:35 AM by Hibernate Tools 4.3.1.Final

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * StatusKawin generated by hbm2java
 */
@Entity
@Table(name = "status_kawin", schema = "public")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class StatusKawin implements java.io.Serializable {

	private static final long serialVersionUID = -2410368128469015170L;

	@Id
	@Column(name = "status_kawin_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_status_kawin_status_kawin_id_seq")
	@SequenceGenerator(name="generator_status_kawin_status_kawin_id_seq", sequenceName="status_kawin_status_kawin_id_seq", schema = "public", allocationSize = 1)
	private long statusKawinId;

	@Column(name = "nama_status")
	private String namaStatus;

	@Column(name = "status_active")
	private Boolean statusActive;

	public StatusKawin(long statusKawinId) {
		this.statusKawinId = statusKawinId;
	}
}
